spring:
  application:
    name: headblog
  datasource:
    url: jdbc:postgresql://localhost:5432/headblog
    username: headblog
    password: headblog
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

jwt:
  secret: "BzFwqL2+1XKvNmL9RzGv3J0RwskKPJ4JmC3TPwmKS0v3JK9L4Km6RX3JL="
  expiration: 1800000 # 30分（ミリ秒単位で設定）

logging:
  level:
    org.flywaydb: DEBUG
    org.jooq: DEBUG

server:
  port: 8080
